const ACTION_TYPES = {
    ADD_LOG_ENTRY: "ADD_LOG_ENTRY",
    APP_INIT_SUCCESS: "APP_INIT_SUCCESS",
    RESIZE: "RESIZE",
    SELECT_BINDING: "SELECT_BINDING",
    SELECT_KERNEL: "SELECT_KERNEL",
    SELECT_LOG_ENTRY: "SELECT_LOG_ENTRY"
};

export default ACTION_TYPES;
