const ACTION_TYPES = {
    ADD_LOG_ENTRY: "ADD_LOG_ENTRY",
    APP_INIT_SUCCESS: "APP_INIT_SUCCESS",
    APP_SETTINGS_SUCCESS: "APP_SETTINGS_SUCCESS",
    CLEAR_LOG: "CLEAR_LOG",
    FILTER_LOG_ENTRIES: "FILTER_LOG_ENTRIES",
    KERNEL_CONNECT_SUCCESS: "KERNEL_CONNECT_SUCCESS",
    RESIZE: "RESIZE",
    SAVE_SETTINGS_ERROR: "SAVE_SETTINGS_ERROR",
    SAVE_SETTINGS_SUCCESS: "SAVE_SETTINGS_SUCCESS",
    SELECT_BINDING: "SELECT_BINDING",
    SELECT_KERNEL: "SELECT_KERNEL",
    SELECT_LOG_ENTRY: "SELECT_LOG_ENTRY"
};

export default ACTION_TYPES;
